### PR TITLE
Add release with CI

### PR DESCRIPTION
**Pull request by sandhilt**
### Description

This PR introduces the following changes:

- **Ignored environment-specific files**: Adjustments made to the `.gitignore` to exclude files specific to development environments.
- **CI Integration**: Added Continuous Integration (CI) using GitHub Actions for building and delivering binaries.
- **Message package Improvements**: Replaced the broken `LocalWallet` with `PrivateKeySigner` in the test suite.
- **Permissive CI Tests**: Tests within the CI are currently permissive while further improvements are under development.
- **Workspace Enablement**: The workspace remains enabled for the time being.

### Known Issue

There is a test failure that needs to be addressed:
```shell
---- tests::test stdout ----
thread 'tests::test' panicked at message/src/lib.rs:398:9:
assertion `left == right` failed
  left: "{\"r\":\"0xfa6f7fd6825c953b355c8970fd2c9322162987bfb6898aa78f74f2be6bf8b10c\",\"s\":\"0x9a2018a7e31b623a91802147e6f8d5c658e17191e69f6663052efda71db72e2\",\"yParity\":\"0x1\"}"
 right: "{\"r\":\"0x1551fdb98e7afaedf0f626029e525ff7ca4b8e8bad81f2d7299979d76ed438b3\",\"s\":\"0x726fc8b549d8578868775530eee59c9c2b57923baef9df981280739f1b76289e\",\"yParity\":\"0x0\"}"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### CODE REVIEW

**Review by fabiooshiro — APPROVED** [review]
LGTM!

**Review by fabiooshiro — APPROVED** [review]

**Comment by stskeeps** [comment]
This starts anvil before cargo test?

**Comment by sandhilt** [comment]
> This starts anvil before cargo test?

For sure! You can check out:
https://github.com/Calindra/paio/blob/89e45fe8f996d780fc288352eb7f70ba487603ad/.github/workflows/release.yml#L35-L36

https://github.com/foundry-rs/foundry-toolchain/tree/v1

**Comment by stskeeps** [comment]
Odd this test failure happens - what rustc are you on / cargo version? Didn't happen on mine

**Comment by stskeeps** [comment]
Apply this and tests should work again:

```diff --git a/message/src/lib.rs b/message/src/lib.rs
index f39a0e8..1ac70ee 100644
--- a/message/src/lib.rs
+++ b/message/src/lib.rs
@@ -396,7 +396,7 @@ mod tests {
 
         let signature = signer.sign_typed_data_sync(&v, &DOMAIN).unwrap();
         assert_eq!(
-            r#"{"r":"0xfa6f7fd6825c953b355c8970fd2c9322162987bfb6898aa78f74f2be6bf8b10c","s":"0x9a2018a7e31b623a91802147e6f8d5c658e17191e69f6663052efda71db72e2","yParity":"0x1"}"#,
+            r#"{"r":"0x1551fdb98e7afaedf0f626029e525ff7ca4b8e8bad81f2d7299979d76ed438b3","s":"0x726fc8b549d8578868775530eee59c9c2b57923baef9df981280739f1b76289e","yParity":"0x0"}"#,
             serde_json::to_string(&signature).unwrap()
         );
         let signed_tx = SignedTransaction {
@@ -407,7 +407,7 @@ mod tests {
         let ret = serde_json::to_string(&signed_tx).unwrap();
 
         assert_eq!(
-            r#"{"message":{"app":"0x0000000000000000000000000000000000000000","nonce":0,"max_gas_price":0,"data":"0x48656c6c6f2c20576f726c6421"},"signature":{"r":"0xfa6f7fd6825c953b355c8970fd2c9322162987bfb6898aa78f74f2be6bf8b10c","s":"0x9a2018a7e31b623a91802147e6f8d5c658e17191e69f6663052efda71db72e2","yParity":"0x1"}}"#,
+            r#"{"message":{"app":"0x0000000000000000000000000000000000000000","nonce":0,"max_gas_price":0,"data":"0x48656c6c6f2c20576f726c6421"},"signature":{"r":"0x1551fdb98e7afaedf0f626029e525ff7ca4b8e8bad81f2d7299979d76ed438b3","s":"0x726fc8b549d8578868775530eee59c9c2b57923baef9df981280739f1b76289e","yParity":"0x0"}}"#,
             ret
         );
 
@@ -429,7 +429,7 @@ mod tests {
         assert_eq!(signer, recovered);
 
         assert_eq!(
-            r#"{"name":"CartesiPaio","version":"0.0.1","chainId":"0x539","verifyingContract":"0x0000000000000000000000000000000000000000"}"#,
+            r#"{"name":"CartesiPaio","version":"0.0.1","chainId":"0xaa36a7","verifyingContract":"0x0000000000000000000000000000000000000000"}"#,
             serde_json::to_string(&DOMAIN).unwrap()
         );
     }```

**Comment by sandhilt** [comment]
> Apply this and tests should work again:
> 
> ```diff
> index f39a0e8..1ac70ee 100644
> --- a/message/src/lib.rs
> +++ b/message/src/lib.rs
> @@ -396,7 +396,7 @@ mod tests {
>  
>          let signature = signer.sign_typed_data_sync(&v, &DOMAIN).unwrap();
>          assert_eq!(
> -            r#"{"r":"0xfa6f7fd6825c953b355c8970fd2c9322162987bfb6898aa78f74f2be6bf8b10c","s":"0x9a2018a7e31b623a91802147e6f8d5c658e17191e69f6663052efda71db72e2","yParity":"0x1"}"#,
> +            r#"{"r":"0x1551fdb98e7afaedf0f626029e525ff7ca4b8e8bad81f2d7299979d76ed438b3","s":"0x726fc8b549d8578868775530eee59c9c2b57923baef9df981280739f1b76289e","yParity":"0x0"}"#,
>              serde_json::to_string(&signature).unwrap()
>          );
>          let signed_tx = SignedTransaction {
> @@ -407,7 +407,7 @@ mod tests {
>          let ret = serde_json::to_string(&signed_tx).unwrap();
>  
>          assert_eq!(
> -            r#"{"message":{"app":"0x0000000000000000000000000000000000000000","nonce":0,"max_gas_price":0,"data":"0x48656c6c6f2c20576f726c6421"},"signature":{"r":"0xfa6f7fd6825c953b355c8970fd2c9322162987bfb6898aa78f74f2be6bf8b10c","s":"0x9a2018a7e31b623a91802147e6f8d5c658e17191e69f6663052efda71db72e2","yParity":"0x1"}}"#,
> +            r#"{"message":{"app":"0x0000000000000000000000000000000000000000","nonce":0,"max_gas_price":0,"data":"0x48656c6c6f2c20576f726c6421"},"signature":{"r":"0x1551fdb98e7afaedf0f626029e525ff7ca4b8e8bad81f2d7299979d76ed438b3","s":"0x726fc8b549d8578868775530eee59c9c2b57923baef9df981280739f1b76289e","yParity":"0x0"}}"#,
>              ret
>          );
>  
> @@ -429,7 +429,7 @@ mod tests {
>          assert_eq!(signer, recovered);
>  
>          assert_eq!(
> -            r#"{"name":"CartesiPaio","version":"0.0.1","chainId":"0x539","verifyingContract":"0x0000000000000000000000000000000000000000"}"#,
> +            r#"{"name":"CartesiPaio","version":"0.0.1","chainId":"0xaa36a7","verifyingContract":"0x0000000000000000000000000000000000000000"}"#,
>              serde_json::to_string(&DOMAIN).unwrap()
>          );
>      }```
> ```

Ok, i'll apply and test here!

**Comment by sandhilt** [comment]
Done @stskeeps

**Review by stskeeps — APPROVED** [review]

**Pull request merged**
